### ISSUE TITLE
[13.0] internal server error on download

### ISSUE THREAD

**Issue by sbidoul** [OCA/apps-store#78]
I got this when trying to download from https://odoo-community.org/shop/product/mis-builder-budget-1639
```
Traceback (most recent call last):
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/openerp/instance/odoo-community-prod/src/apps-store/website_apps_store/controllers/main.py", line 236, in download_product_zip
    disposition = 'attachment; filename="%s"' % attachment.datas_fname
AttributeError: 'ir.attachment' object has no attribute 'datas_fname'
```

**Comment by pedrobaeza** [comment]
Fixed in 48d0855

**Comment by sbidoul** [comment]
And deployed.

**Comment by pedrobaeza** [comment]
Agh, still with problems. I will test all the flow on local (although it's very complicated due to all the dependencies and pre-requisites). I will tell you when done.

The error is now:
<details>

```
Traceback (most recent call last):
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/openerp/instance/odoo-community-prod/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/openerp/instance/odoo-community-prod/src/apps-store/website_apps_store/controllers/main.py", line 223, in download_product_zip
    product.sudo().generate_zip_file()
  File "/home/openerp/instance/odoo-community-prod/src/apps-store/apps_download/models/product_product.py", line 84, in generate_zip_file
    if product.attribute_value_ids:
AttributeError: 'product.product' object has no attribute 'attribute_value_ids'
```

</details>
